apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "nginx"
  namespace: "sport-activity"
spec:
  rules:
    - host: "api-sportactivity.apociejowski.pl"
      http:
        paths:
          - backend:
              serviceName: "sport-activity-comparison-backend"
              servicePort: 3000
    - host: "sync-sportactivity.apociejowski.pl"
      http:
        paths:
          - backend:
              serviceName: "sport-activity-synchronizer-backend"
              servicePort: 3000
